import { DEVICE_TYPES, DEVICE_CATEGORIES, defaultDevice, computeLinkStates, simulatePing } from "../engine/network.js";
import { CONNECTION_TYPES, CONNECTION_TYPE_MAP, ENDPOINT_INDICATORS, availablePorts, cableForLink, canConnectPorts, endpointIndicatorFor, parallelLinkOffsets, routeConnectionPath, selectAutomaticConnection } from "../engine/connections.js";
import { deviceIcon } from "../devices/icons.js";
import { CLI } from "../cli/cli.js";
const $=s=>document.querySelector(s); const state={version:2,devices:[],links:[],counters:{},selected:null,tool:"select",connectSource:null,connectSourcePort:null,connectTarget:null,selectedCable:"automatic",reconnect:null};
const workspace=$("#workspace"),links=$("#linkLayer"),palette=$("#devicePalette"),inspector=$("#inspectorContent"),windowLayer=$("#windowLayer");
const inspectorInterfaceDisplayLimit=14;
let category="routers",drag=null,z=100,activeWindows=new Map();
const categoryIcons={routers:"R",switches:"S",hubs:"H",wireless:"Wi",security:"FW",wan:"WAN",endDevices:"PC",industrial:"IoT",connections:"⚡"};
for(const [key,label] of Object.entries(DEVICE_CATEGORIES)){const b=document.createElement("button");b.textContent=categoryIcons[key]||label.slice(0,2);b.title=label;b.setAttribute("aria-label",label);b.onclick=()=>{category=key;renderPalette()};$("#categoryTabs").appendChild(b)}
function renderPalette(){const keys=Object.keys(DEVICE_CATEGORIES);[...$("#categoryTabs").children].forEach((b,i)=>b.classList.toggle("active",keys[i]===category));palette.innerHTML="";if(category==="connections")return renderConnectionPalette();for(const [type,def] of Object.entries(DEVICE_TYPES)){if(def.category!==category)continue;const el=document.createElement("div");el.className="palette-item";el.draggable=true;el.innerHTML=`${deviceIcon(def.icon)}<div class="palette-label">${def.label}</div>`;el.addEventListener("dragstart",e=>e.dataTransfer.setData("device-type",type));palette.appendChild(el)}}
function renderConnectionPalette(){palette.appendChild(connectionLegend());for(const cable of CONNECTION_TYPES)palette.appendChild(connectionPaletteItem(cable))}
function connectionLegend(){const legend=document.createElement("div");legend.className="connection-legend";legend.innerHTML=`<h3>Connection Legend</h3><p>Select a cable, then choose compatible devices and ports. Endpoint symbols use the documented approximation below until exact Packet Tracer state shapes are verified.</p><div class="indicator-legend">${Object.values(ENDPOINT_INDICATORS).map(i=>`<span><b class="endpoint-legend-marker" style="--endpoint:${i.color}">${esc(i.symbol)}</b>${esc(i.label)}</span>`).join("")}</div>`;return legend}
function connectionPaletteItem(cable){const el=document.createElement("button");el.type="button";el.className="connection-item"+(state.selectedCable===cable.key?" selected":"");el.title=cable.label;el.setAttribute("aria-label",cable.label);el.innerHTML=`<span class="cable-icon" style="--cable:${cable.color}">${esc(cable.icon)}</span><span>${esc(cable.label)}</span>`;el.onclick=()=>{state.selectedCable=cable.key;setTool("connect");renderPalette();renderInspector();status(`Selected ${cable.label}.`)};return el}
workspace.addEventListener("dragover",e=>e.preventDefault());workspace.addEventListener("drop",e=>{e.preventDefault();const type=e.dataTransfer.getData("device-type");if(!DEVICE_TYPES[type])return;const r=workspace.getBoundingClientRect();addDevice(type,e.clientX-r.left+workspace.parentElement.scrollLeft,e.clientY-r.top+workspace.parentElement.scrollTop)});
function uid(p){
  const hasRandomUUID=window.crypto&&typeof window.crypto.randomUUID==="function";
  return `${p}-${hasRandomUUID?window.crypto.randomUUID():Math.random().toString(36).slice(2)}`;
}
function addDevice(type,x,y){state.counters[type]=(state.counters[type]||0)+1;state.devices.push(defaultDevice(type,uid("dev"),Math.max(0,x-56),Math.max(0,y-39),state.counters[type]));render();persist()}
function render(){computeLinkStates(state);workspace.querySelectorAll(".device").forEach(e=>e.remove());links.innerHTML="";$("#emptyHint").style.display=state.devices.length?"none":"block";state.links.forEach(drawLink);drawReconnectPreview();state.devices.forEach(drawDevice);renderInspector()}
function drawDevice(d){const def=DEVICE_TYPES[d.type],el=document.createElement("div"),selectedId=state.selected&&state.selected.id;el.className="device"+(selectedId===d.id?" selected":"")+(state.connectSource===d.id?" connect-source":"")+(compatibleReconnectDevice(d)?" compatible-target":"");el.style.left=d.x+"px";el.style.top=d.y+"px";el.dataset.deviceId=d.id;el.innerHTML=`<div class="device-leds"><i></i><i></i></div>${deviceIcon(def.icon)}<div class="device-name">${esc(d.name)}</div><div class="device-model">${def.label}</div>`;el.addEventListener("pointerdown",e=>beginDeviceDrag(e,d,el));el.addEventListener("click",e=>{e.stopPropagation();deviceClick(d)});el.addEventListener("dblclick",e=>{e.stopPropagation();if(!drag||!drag.moved)openDeviceWindow(d)});workspace.appendChild(el)}
function beginDeviceDrag(e,d,el){if(state.tool!=="select"||state.reconnect||e.button!==0||e.target.closest("button,.port,.endpoint-marker,.window-actions"))return;e.preventDefault();const wr=workspace.getBoundingClientRect();drag={d,el,pointerId:e.pointerId,startX:d.x,startY:d.y,offsetX:e.clientX-wr.left+workspace.parentElement.scrollLeft-d.x,offsetY:e.clientY-wr.top+workspace.parentElement.scrollTop-d.y,moved:false};if(typeof el.setPointerCapture==="function")el.setPointerCapture(e.pointerId);document.addEventListener("pointermove",moveDevice);document.addEventListener("pointerup",endDevice,{once:true})}
function moveDevice(e){if(!drag)return;const wr=workspace.getBoundingClientRect(),maxX=workspace.clientWidth-drag.el.offsetWidth,maxY=workspace.clientHeight-drag.el.offsetHeight;const nx=Math.max(0,Math.min(maxX,e.clientX-wr.left+workspace.parentElement.scrollLeft-drag.offsetX)),ny=Math.max(0,Math.min(maxY,e.clientY-wr.top+workspace.parentElement.scrollTop-drag.offsetY));if(Math.hypot(nx-drag.startX,ny-drag.startY)>4)drag.moved=true;drag.d.x=nx;drag.d.y=ny;drag.el.style.left=nx+"px";drag.el.style.top=ny+"px";updateConnectedLines()}
function endDevice(){document.removeEventListener("pointermove",moveDevice);if(drag?.el&&typeof drag.el.releasePointerCapture==="function"&&typeof drag.el.hasPointerCapture==="function"&&drag.el.hasPointerCapture(drag.pointerId))drag.el.releasePointerCapture(drag.pointerId);if(drag&&drag.moved){state.selected={kind:"device",id:drag.d.id};persist();render()}drag=null}
function updateConnectedLines(){const offsets=parallelLinkOffsets(state.links);state.links.forEach(l=>{const route=routeConnectionPath(l,state,{offset:offsets.get(l.id)||0});if(!route)return;const g=links.querySelector(`[data-link-id="${l.id}"]`);if(!g)return;g.querySelectorAll(".link-line,.link-hit").forEach(p=>p.setAttribute("d",route.path));const label=g.querySelector(".link-label");if(label){label.setAttribute("x",route.mid.x);label.setAttribute("y",route.mid.y-6)}setEndpointPosition(g.querySelector('[data-side="a"]'),route.start);setEndpointPosition(g.querySelector('[data-side="b"]'),route.end)})}
function drawLink(l){const route=routeConnectionPath(l,state,{offset:parallelLinkOffsets(state.links).get(l.id)||0});if(!route)return;const linkCable=cableForLink(l),cable=CONNECTION_TYPE_MAP[l.resolvedCableType||linkCable]||CONNECTION_TYPE_MAP.automatic,g=svg("g");g.dataset.linkId=l.id;g.setAttribute("class","link-group"+(state.selected&&state.selected.kind==="link"&&state.selected.id===l.id?" selected":""));const hit=svg("path"),line=svg("path");hit.setAttribute("class","link-hit");hit.setAttribute("d",route.path);line.setAttribute("class",`link-line ${l.up?"up":"down"}`);line.setAttribute("d",route.path);line.style.stroke=l.up?cable.color:"#c94444";const title=svg("title");title.textContent=linkTitle(l,cable);g.append(hit,line,title,linkLabel(l,cable,route),endpointMarker(l,"a",route.start),endpointMarker(l,"b",route.end));g.addEventListener("click",e=>{e.stopPropagation();state.selected={kind:"link",id:l.id};render()});links.appendChild(g)}
function svg(name){return document.createElementNS("http://www.w3.org/2000/svg",name)}
function linkLabel(l,cable,route){const t=svg("text");t.setAttribute("class","link-label");t.setAttribute("x",route.mid.x);t.setAttribute("y",route.mid.y-6);t.textContent=cable.icon;return t}
function endpointMarker(l,side,point){const info=endpointIndicatorFor(state,l,side),g=svg("g"),c=svg("circle"),txt=svg("text"),title=svg("title");g.setAttribute("class",`endpoint-marker ${info.shape}`);g.dataset.linkId=l.id;g.dataset.side=side;g.style.setProperty("--endpoint",info.color);setEndpointPosition(g,point);c.setAttribute("r","8");txt.setAttribute("text-anchor","middle");txt.setAttribute("dominant-baseline","central");txt.textContent=info.symbol;title.textContent=endpointTitle(l,side,info);g.append(c,txt,title);g.addEventListener("click",e=>{e.stopPropagation();beginReconnect(l,side,e)});return g}
function setEndpointPosition(g,point){if(!g||!point)return;g.setAttribute("transform",`translate(${point.x} ${point.y})`)}
function linkTitle(l,cable){const a=state.devices.find(d=>d.id===l.a.deviceId),b=state.devices.find(d=>d.id===l.b.deviceId);return `${cable.label}: ${a?.name||"disconnected"} ${l.a.port||""} ↔ ${b?.name||"disconnected"} ${l.b.port||""}. ${l.status||""}`}
function endpointTitle(l,side,info){const e=l[side],d=state.devices.find(x=>x.id===e.deviceId);return `${d?.name||"Disconnected"} ${e.port||""}: ${info.label}. Click to unplug and reconnect this side.`}
function beginReconnect(l,side,e){const original={...l[side]},peer=side==="a"?"b":"a";releaseEndpoint(l,side);state.reconnect={linkId:l.id,side,peer,original,targetDevice:null,pointer:pointerPoint(e)};state.selected={kind:"link",id:l.id};setTool("select");status(`Reconnect ${original.port}. Select a compatible destination device and port, or press Escape to cancel.`);document.addEventListener("pointermove",trackReconnectPointer);render()}
function releaseEndpoint(l,side){const endpoint=l[side],dev=state.devices.find(d=>d.id===endpoint.deviceId),intf=dev?.config.interfaces?.[endpoint.port];if(intf){if(intf.connectedLinkId===l.id)intf.connectedLinkId=null;if(intf.cableConnection===l.id)intf.cableConnection=null}l[side]={deviceId:null,port:null};l.up=false;l.status="Cable disconnected at one end"}
function attachEndpoint(l,side,dev,port){l[side]={deviceId:dev.id,port:port.name};if(port.interfaceType!=="wireless")port.connectedLinkId=l.id;port.cableConnection=l.id}
function pointerPoint(e){const wr=workspace.getBoundingClientRect();return {x:e.clientX-wr.left+workspace.parentElement.scrollLeft,y:e.clientY-wr.top+workspace.parentElement.scrollTop}}
function trackReconnectPointer(e){if(!state.reconnect)return;state.reconnect.pointer=pointerPoint(e);drawReconnectPreview(true)}
function drawReconnectPreview(updateOnly=false){if(updateOnly)links.querySelectorAll(".reconnect-preview").forEach(e=>e.remove());if(!state.reconnect)return;const l=state.links.find(x=>x.id===state.reconnect.linkId);if(!l)return;const peer=l[state.reconnect.peer],dev=state.devices.find(d=>d.id===peer.deviceId);if(!dev)return;const start=routeConnectionPath({...l,[state.reconnect.side]:peer},state)?.start;if(!start)return;const end=state.reconnect.pointer||start,g=svg("g"),p=svg("path");g.setAttribute("class","reconnect-preview");p.setAttribute("class","link-line down");p.setAttribute("d",`M ${start.x} ${start.y} L ${end.x} ${end.y}`);g.append(p);links.appendChild(g)}
function compatibleReconnectDevice(d){if(!state.reconnect)return false;const l=state.links.find(x=>x.id===state.reconnect.linkId),peer=l&&l[state.reconnect.peer];if(!l||!peer)return false;const peerDevice=state.devices.find(x=>x.id===peer.deviceId),peerPort=peerDevice?.config.interfaces?.[peer.port],cable=l.resolvedCableType||cableForLink(l);return !!Object.values(d.config.interfaces||{}).find(p=>canConnectPorts(cable,d,p,peerDevice,peerPort,{ignoreLinkId:l.id}).ok)}
function reconnectDeviceClick(d){if(!compatibleReconnectDevice(d)){status("That device has no compatible free port for this cable.");return}state.reconnect.targetDevice=d.id;render()}
function reconnectToPort(portName){const r=state.reconnect,l=state.links.find(x=>x.id===r.linkId);if(!l)return cancelReconnect();const target=state.devices.find(d=>d.id===r.targetDevice),peerDev=state.devices.find(d=>d.id===l[r.peer].deviceId),targetPort=target?.config.interfaces?.[portName],peerPort=peerDev?.config.interfaces?.[l[r.peer].port],cable=l.resolvedCableType||cableForLink(l),validation=canConnectPorts(cable,target,targetPort,peerDev,peerPort,{ignoreLinkId:l.id});if(!validation.ok)return status(validation.reason);attachEndpoint(l,r.side,target,targetPort);state.reconnect=null;document.removeEventListener("pointermove",trackReconnectPointer);status(`Reconnected ${target.name} ${targetPort.name}.`);render();persist()}
function cancelReconnect(){const r=state.reconnect;if(!r)return;const l=state.links.find(x=>x.id===r.linkId),dev=state.devices.find(d=>d.id===r.original.deviceId),port=dev?.config.interfaces?.[r.original.port];if(l&&dev&&port)attachEndpoint(l,r.side,dev,port);state.reconnect=null;document.removeEventListener("pointermove",trackReconnectPointer);status("Reconnect canceled; original endpoint restored.");render();persist()}
function deviceClick(d){if(drag&&drag.moved)return;if(state.reconnect)return reconnectDeviceClick(d);if(state.tool==="delete")return removeDevice(d.id);if(state.tool==="connect")return connectionDeviceClick(d);state.selected={kind:"device",id:d.id};render()}
function connectionDeviceClick(d){state.selected=null;if(!state.connectSource){state.connectSource=d.id;state.connectSourcePort=null;state.connectTarget=null;status(state.selectedCable==="automatic"?`Select the device to connect to ${d.name}.`:`Select an available ${CONNECTION_TYPE_MAP[state.selectedCable].label} port on ${d.name}.`);return render()}if(state.selectedCable==="automatic"){if(state.connectSource===d.id){clearConnectionFlow();return render()}connectAutomatic(state.connectSource,d.id);clearConnectionFlow();render();persist();return}if(!state.connectSourcePort){state.connectSource=d.id;status(`Choose the first port on ${d.name}.`);return render()}if(state.connectSource===d.id){state.connectTarget=null;status("Select a different second device.");return renderInspector()}state.connectTarget=d.id;status(`Choose a compatible port on ${d.name}.`);renderInspector()}
function connectAutomatic(aid,bid){const a=state.devices.find(d=>d.id===aid),b=state.devices.find(d=>d.id===bid),choice=selectAutomaticConnection(a,b);if(!choice.ok)return status(choice.reason);createLink(a,b,choice.aPort,choice.bPort,"automatic",choice.cableType);status(choice.reason)}
function connectManual(targetPortName){const a=state.devices.find(d=>d.id===state.connectSource),b=state.devices.find(d=>d.id===state.connectTarget),ap=a&&a.config.interfaces[state.connectSourcePort],bp=b&&b.config.interfaces[targetPortName],validation=canConnectPorts(state.selectedCable,a,ap,b,bp);if(!validation.ok)return status(validation.reason);createLink(a,b,ap,bp,state.selectedCable,state.selectedCable);status(`Connected ${a.name} ${ap.name} to ${b.name} ${bp.name} with ${CONNECTION_TYPE_MAP[state.selectedCable].label}.`);clearConnectionFlow();render();persist()}
function createLink(a,b,ap,bp,cableType,resolvedCableType){const id=uid("link");state.links.push({id,type:cableType,cableType,resolvedCableType,a:{deviceId:a.id,port:ap.name},b:{deviceId:b.id,port:bp.name},up:false,status:"Pending"});if(ap.interfaceType!=="wireless")ap.connectedLinkId=id;if(bp.interfaceType!=="wireless")bp.connectedLinkId=id;ap.cableConnection=id;bp.cableConnection=id}
function clearConnectionFlow(){state.connectSource=null;state.connectSourcePort=null;state.connectTarget=null}
function removeDevice(id){state.links.filter(l=>l.a.deviceId===id||l.b.deviceId===id).forEach(l=>removeLink(l.id,false));state.devices=state.devices.filter(d=>d.id!==id);state.selected=null;const win=activeWindows.get(id);if(win)win.remove();activeWindows.delete(id);render();persist()}
function removeLink(id,shouldRender=true){for(const d of state.devices)for(const i of Object.values(d.config.interfaces)){if(i.connectedLinkId===id)i.connectedLinkId=null;if(i.cableConnection===id)i.cableConnection=null}state.links=state.links.filter(l=>l.id!==id);state.selected=null;if(shouldRender){render();persist()}}
workspace.addEventListener("click",()=>{state.selected=null;render()});
function renderInspector(){if(state.reconnect)return renderReconnectInspector();if(state.tool==="connect"&&!state.selected)return renderConnectionInspector();if(!state.selected){inspector.innerHTML="<p>Select a device or connection.</p>";return}if(state.selected.kind==="link"){const l=state.links.find(x=>x.id===state.selected.id);if(!l){state.selected=null;inspector.innerHTML="<p>Select a device or connection.</p>";return}const a=state.devices.find(d=>d.id===l.a.deviceId),b=state.devices.find(d=>d.id===l.b.deviceId),c=CONNECTION_TYPE_MAP[l.resolvedCableType||cableForLink(l)]||CONNECTION_TYPE_MAP.automatic;inspector.innerHTML=`<b>${l.up?"Operational":"Down"}</b><p><b>Cable:</b> ${esc(c.label)}</p><p><b>Status:</b> ${esc(l.status||"Unknown")}</p><p>${esc(a?.name||"Disconnected")}<br>${esc(l.a.port||"-")}</p><p>to</p><p>${esc(b?.name||"Disconnected")}<br>${esc(l.b.port||"-")}</p><button id="delLink">Delete connection</button>`;$("#delLink").onclick=()=>removeLink(l.id);return}const d=state.devices.find(x=>x.id===state.selected.id);const rows=Object.values(d.config.interfaces).slice(0,inspectorInterfaceDisplayLimit).map(interfaceRow).join("");inspector.innerHTML=`<label>Display name<input id="devName" value="${esc(d.name)}"></label><label>Power<select id="power"><option value="on" ${d.enabled?"selected":""}>On</option><option value="off" ${!d.enabled?"selected":""}>Off</option></select></label><button id="openDevice">Open Device</button><h4>Interfaces</h4><table class="interface-table"><tr><th>Port</th><th>IP</th><th>State</th></tr>${rows}</table>`;$("#devName").onchange=e=>{d.name=e.target.value;d.config.hostname=e.target.value;render();persist()};$("#power").onchange=e=>{d.enabled=e.target.value==="on";d.config.physical.power=d.enabled;render();persist()};$("#openDevice").onclick=()=>openDeviceWindow(d)}
function renderReconnectInspector(){const r=state.reconnect,l=state.links.find(x=>x.id===r.linkId),c=CONNECTION_TYPE_MAP[l?.resolvedCableType||cableForLink(l)]||CONNECTION_TYPE_MAP.automatic,target=state.devices.find(d=>d.id===r.targetDevice),peer=state.devices.find(d=>d.id===l?.[r.peer]?.deviceId),peerPort=peer?.config.interfaces?.[l?.[r.peer]?.port];if(!l||!peer||!peerPort){inspector.innerHTML="<p>Reconnect state is invalid.</p><button id='cancelReconnect'>Cancel</button>";$("#cancelReconnect").onclick=cancelReconnect;return}if(!target){inspector.innerHTML=`<h3>Reconnect endpoint</h3><p><b>Cable:</b> ${esc(c.label)}</p><p>Still connected: <b>${esc(peer.name)} ${esc(peerPort.name)}</b></p><p>Select a highlighted compatible device, then choose a port.</p><button id="cancelReconnect">Cancel reconnect</button>`;$("#cancelReconnect").onclick=cancelReconnect;return}const ports=Object.values(target.config.interfaces).filter(p=>canConnectPorts(l.resolvedCableType||cableForLink(l),target,p,peer,peerPort,{ignoreLinkId:l.id}).ok);inspector.innerHTML=`<h3>Reconnect endpoint</h3><p>Destination: <b>${esc(target.name)}</b></p>${portChoiceList(ports,"No compatible free ports on this device.")}<button id="cancelReconnect">Cancel reconnect</button>`;inspector.querySelectorAll("[data-port]").forEach(b=>b.onclick=()=>reconnectToPort(b.dataset.port));$("#cancelReconnect").onclick=cancelReconnect}
function interfaceRow(i){const stateText=i.shutdown?"down":"up",stateTitle=i.shutdown?"Interface administratively down":"Interface operationally up";return `<tr><td>${esc(i.name)}<br><small>${esc(i.abbreviation||"")} ${esc(i.connectorType||"")}</small></td><td>${esc(i.ip||"-")}</td><td><span title="${stateTitle}" aria-label="${stateTitle}">${stateText}</span></td></tr>`}
function renderConnectionInspector(){
  const cable=CONNECTION_TYPE_MAP[state.selectedCable]||CONNECTION_TYPE_MAP.automatic;
  if(!state.connectSource)return renderNoSourceConnectionInspector(cable);
  const source=state.devices.find(d=>d.id===state.connectSource);
  if(!source){clearConnectionFlow();return renderConnectionInspector()}
  if(state.selectedCable==="automatic")return renderAutomaticConnectionInspector(source);
  if(!state.connectSourcePort)return renderSourcePortInspector(cable,source);
  if(!state.connectTarget)return renderTargetDeviceInspector(cable,source);
  return renderTargetPortInspector(cable,source);
}
function renderNoSourceConnectionInspector(cable){inspector.innerHTML=`<h3>Connections</h3><p><b>Selected:</b> ${esc(cable.label)}</p><p>Choose the first device on the canvas.</p><button id="showConnections">Open connection palette</button>`;$("#showConnections").onclick=()=>{category="connections";renderPalette()}}
function renderAutomaticConnectionInspector(source){inspector.innerHTML=`<h3>Automatic connection</h3><p>First device: <b>${esc(source.name)}</b></p><p>Select the second device. The simulator will choose a compatible cable and free ports.</p><button id="cancelConnect">Cancel</button>`;bindCancelConnection()}
function renderSourcePortInspector(cable,source){const ports=availablePorts(source,state.selectedCable);inspector.innerHTML=`<h3>${esc(cable.label)}</h3><p>First device: <b>${esc(source.name)}</b></p><p>Compatible available ports:</p>${portChoiceList(ports,"No compatible available ports.")}<button id="cancelConnect">Cancel</button>`;inspector.querySelectorAll("[data-port]").forEach(b=>b.onclick=()=>{state.connectSourcePort=b.dataset.port;status(`Selected ${source.name} ${b.dataset.port}. Select the second device.`);renderInspector()});bindCancelConnection()}
function renderTargetDeviceInspector(cable,source){inspector.innerHTML=`<h3>${esc(cable.label)}</h3><p>First endpoint: <b>${esc(source.name)} ${esc(state.connectSourcePort)}</b></p><p>Select the second device.</p><button id="cancelConnect">Cancel</button>`;bindCancelConnection()}
function renderTargetPortInspector(cable,source){const target=state.devices.find(d=>d.id===state.connectTarget),sourcePort=source.config.interfaces[state.connectSourcePort],ports=target?availablePorts(target,state.selectedCable,{device:source,port:sourcePort}):[];inspector.innerHTML=`<h3>${esc(cable.label)}</h3><p>First endpoint: <b>${esc(source.name)} ${esc(sourcePort.name)}</b></p><p>Second device: <b>${esc(target.name)}</b></p><p>Compatible available ports:</p>${portChoiceList(ports,"No compatible available ports on this device.")}<button id="cancelConnect">Cancel</button>`;inspector.querySelectorAll("[data-port]").forEach(b=>b.onclick=()=>connectManual(b.dataset.port));bindCancelConnection()}
function portChoiceList(ports,emptyText){const buttons=ports.map(p=>`<button data-port="${esc(p.name)}">${esc(p.name)} <small>${esc(p.connectorType)}</small></button>`).join("");return `<div class="port-choice-list">${buttons||`<em>${esc(emptyText)}</em>`}</div>`}
function bindCancelConnection(){const button=$("#cancelConnect");if(button)button.onclick=()=>{clearConnectionFlow();render()}}
function openDeviceWindow(d){let win=activeWindows.get(d.id);if(win){win.style.zIndex=++z;return}const frag=$("#deviceWindowTemplate").content.cloneNode(true);win=frag.querySelector(".device-window");win.dataset.deviceId=d.id;win.style.left=`${Math.min(160+activeWindows.size*28,window.innerWidth-560)}px`;win.style.top=`${Math.min(90+activeWindows.size*24,window.innerHeight-420)}px`;win.style.zIndex=++z;win.querySelector(".window-title").textContent=d.name;win.querySelector(".window-model").textContent=DEVICE_TYPES[d.type].label;const tabs=deviceTabs(d);const nav=win.querySelector(".window-tabs");tabs.forEach((t,i)=>{const b=document.createElement("button");b.textContent=t;b.onclick=()=>showTab(win,d,t);if(i===0)b.classList.add("active");nav.appendChild(b)});win.querySelector('[data-action="close"]').onclick=()=>{activeWindows.delete(d.id);win.remove()};win.querySelector('[data-action="pin"]').onclick=e=>{win.classList.toggle("pinned");e.currentTarget.textContent=win.classList.contains("pinned")?"◆":"◇"};makeWindowDraggable(win);windowLayer.appendChild(win);activeWindows.set(d.id,win);showTab(win,d,tabs[0])}
function deviceTabs(d){const base=["Physical","Config"];if(d.capabilities.desktop)base.push("Desktop");if(d.capabilities.cli)base.push("CLI");if(DEVICE_TYPES[d.type].kind==="server")base.push("Services");if(["wireless-router","access-point"].includes(DEVICE_TYPES[d.type].kind))base.push("GUI");return base}
function showTab(win,d,tab){[...win.querySelectorAll(".window-tabs button")].forEach(b=>b.classList.toggle("active",b.textContent===tab));const c=win.querySelector(".window-content");if(tab==="Physical")renderPhysical(c,d);if(tab==="Config")renderConfig(c,d);if(tab==="Desktop")renderDesktop(c,d);if(tab==="CLI")renderCli(c,d);if(tab==="Services")renderServices(c,d);if(tab==="GUI")renderWirelessGui(c,d)}
function renderPhysical(c,d){c.innerHTML=`<div class="physical-view"><div class="chassis">${deviceIcon(DEVICE_TYPES[d.type].icon)}</div><div><h3>${d.model}</h3><label><input type="checkbox" id="physicalPower" ${d.config.physical.power?"checked":""}> Power</label><p>Module support is prepared for future hot-swappable hardware and cable compatibility.</p><h4>Installed interfaces</h4>${Object.keys(d.config.interfaces).join("<br>")}</div></div>`;c.querySelector("#physicalPower").onchange=e=>{d.config.physical.power=e.target.checked;d.enabled=e.target.checked;render();persist()}}
function renderConfig(c,d){const interfaces=Object.keys(d.config.interfaces);c.innerHTML=`<div class="config-sections"><div class="config-nav"><button data-page="global">GLOBAL Settings</button>${interfaces.map(n=>`<button data-page="${esc(n)}">${n}</button>`).join("")}</div><div class="config-pane"></div></div>`;const pane=c.querySelector(".config-pane");const show=page=>{if(page==="global"){pane.innerHTML=`<h3>Global Settings</h3><div class="form-grid"><label>Display Name</label><input id="cfgName" value="${esc(d.name)}"><label>Hostname</label><input id="cfgHost" value="${esc(d.config.hostname)}"><label>Default Gateway</label><input id="cfgGw" value="${esc(d.config.ipSettings.gateway)}"></div>`;pane.querySelector("#cfgName").onchange=e=>{d.name=e.target.value;winTitle(d);render();persist()};pane.querySelector("#cfgHost").onchange=e=>{d.config.hostname=e.target.value;persist()};pane.querySelector("#cfgGw").onchange=e=>{d.config.ipSettings.gateway=e.target.value;persist()}}else{const i=d.config.interfaces[page];pane.innerHTML=`<h3>${page}</h3><div class="form-grid"><label>Port Status</label><select id="ifState"><option value="up" ${!i.shutdown?"selected":""}>On</option><option value="down" ${i.shutdown?"selected":""}>Off</option></select><label>IPv4 Address</label><input id="ifIp" value="${esc(i.ip)}"><label>Subnet Mask</label><input id="ifMask" value="${esc(i.mask)}"><label>IPv6 Address</label><input id="ifV6" value="${esc(i.ipv6)}"><label>VLAN</label><input id="ifVlan" type="number" value="${i.vlan}"><label>Switchport Mode</label><select id="ifMode"><option ${i.mode==="access"?"selected":""}>access</option><option ${i.mode==="trunk"?"selected":""}>trunk</option></select><label>MAC Address</label><input disabled value="${i.mac}"></div>`;pane.querySelector("#ifState").onchange=e=>{i.shutdown=e.target.value==="down";render();persist()};pane.querySelector("#ifIp").onchange=e=>{i.ip=e.target.value;persist()};pane.querySelector("#ifMask").onchange=e=>{i.mask=e.target.value;persist()};pane.querySelector("#ifV6").onchange=e=>{i.ipv6=e.target.value;persist()};pane.querySelector("#ifVlan").onchange=e=>{i.vlan=Number(e.target.value)||1;persist()};pane.querySelector("#ifMode").onchange=e=>{i.mode=e.target.value;persist()}}};c.querySelectorAll(".config-nav button").forEach(b=>b.onclick=()=>show(b.dataset.page));show("global")}
function winTitle(d){const w=activeWindows.get(d.id);if(w)w.querySelector(".window-title").textContent=d.name}
function renderDesktop(c,d){const apps=[["IP Configuration","⌘"],["Terminal","▣"],["Command Prompt",">_"],["Web Browser","◎"],["PC Wireless","≋"],["VPN","◈"],["Traffic Generator","⇄"],["Text Editor","T"],["Firewall","▦"]];c.innerHTML=`<div class="desktop-grid">${apps.map(([n,i])=>`<button class="desktop-app" data-app="${n}"><b>${i}</b>${n}</button>`).join("")}</div>`;c.querySelectorAll(".desktop-app").forEach(b=>b.onclick=()=>openDesktopApp(c,d,b.dataset.app))}
function openDesktopApp(c,d,app){if(app==="IP Configuration"){const s=d.config.ipSettings;c.innerHTML=`<button id="backDesktop">← Back</button><h3>IP Configuration</h3><label><input type="radio" name="mode" value="dhcp" ${s.dhcp?"checked":""}> DHCP</label> <label><input type="radio" name="mode" value="static" ${!s.dhcp?"checked":""}> Static</label><div class="form-grid"><label>IPv4 Address</label><input id="deskIp" value="${esc(s.ip)}"><label>Subnet Mask</label><input id="deskMask" value="${esc(s.mask)}"><label>Default Gateway</label><input id="deskGw" value="${esc(s.gateway)}"><label>DNS Server</label><input id="deskDns" value="${esc(s.dns)}"><label>IPv6 Address</label><input id="deskV6" value="${esc(s.ipv6)}"><label>IPv6 Gateway</label><input id="deskV6Gw" value="${esc(s.ipv6Gateway)}"></div>`;c.querySelector("#backDesktop").onclick=()=>renderDesktop(c,d);c.querySelectorAll('[name="mode"]').forEach(r=>r.onchange=e=>{s.dhcp=e.target.value==="dhcp";persist()});[["deskIp","ip"],["deskMask","mask"],["deskGw","gateway"],["deskDns","dns"],["deskV6","ipv6"],["deskV6Gw","ipv6Gateway"]].forEach(([id,k])=>c.querySelector("#"+id).onchange=e=>{s[k]=e.target.value;const first=Object.values(d.config.interfaces).find(i=>i.name!=="RS232"&&i.name!=="Wireless0");if(first&&k==="ip")first.ip=e.target.value;if(first&&k==="mask")first.mask=e.target.value;persist()})}else if(["Command Prompt","Terminal"].includes(app)){renderCli(c,d,true)}else{c.innerHTML=`<button id="backDesktop">← Back</button><h3>${app}</h3><p>This application shell is installed. Its protocol engine will be connected in the protocol milestones.</p>`;c.querySelector("#backDesktop").onclick=()=>renderDesktop(c,d)}}
function renderCli(c,d,desktop=false){const cli=new CLI(state,d,()=>{render();persist()});c.innerHTML=`<div class="terminal"><div class="terminal-output">BrittsPacketTracer IOS-compatible simulation\n${desktop?"PC Command Prompt":""}\n\n</div><div class="terminal-row"><span class="prompt"></span><input autocomplete="off" spellcheck="false"></div></div>`;const out=c.querySelector(".terminal-output"),input=c.querySelector("input"),prompt=c.querySelector(".prompt");const update=()=>prompt.textContent=desktop?"C:\\>":cli.prompt();update();input.focus();input.onkeydown=e=>{if(e.key==="Enter"){const cmd=input.value,result=desktop&&!(cmd.toLowerCase().startsWith("ping")||cmd.toLowerCase().startsWith("tracert")||cmd.toLowerCase()==="ipconfig")?"'"+cmd+"' is not recognized as an internal or external command.":desktopCommand(cmd,d,cli);out.textContent+=`${desktop?"C:\\>":cli.prompt()}${cmd}\n${result?result+"\n":""}`;input.value="";update();out.scrollTop=out.scrollHeight}else if(e.key==="ArrowUp"){e.preventDefault();cli.historyIndex=Math.max(0,cli.historyIndex-1);input.value=cli.history[cli.historyIndex]||""}}}
function desktopCommand(cmd,d,cli){const low=cmd.toLowerCase().trim();if(low==="ipconfig"||low==="ipconfig /all"){const s=d.config.ipSettings;return `IP Address.............: ${s.ip||"0.0.0.0"}\nSubnet Mask............: ${s.mask||"0.0.0.0"}\nDefault Gateway........: ${s.gateway||"0.0.0.0"}`};if(low.startsWith("tracert "))return cli.execute("traceroute "+cmd.split(/\s+/)[1]);return cli.execute(cmd)}
function renderServices(c,d){c.innerHTML=`<h3>Server Services</h3>${Object.entries(d.config.services).map(([k,v])=>`<label style="display:block;margin:8px"><input type="checkbox" data-service="${k}" ${v?"checked":""}> ${k.toUpperCase()}</label>`).join("")}`;c.querySelectorAll("[data-service]").forEach(x=>x.onchange=e=>{d.config.services[e.target.dataset.service]=e.target.checked;persist()})}
function renderWirelessGui(c,d){const w=d.config.wireless;c.innerHTML=`<h3>Wireless Setup</h3><div class="form-grid"><label>SSID</label><input id="ssid" value="${esc(w.ssid)}"><label>Security</label><select id="security"><option>none</option><option>wpa2-personal</option><option>wpa3-personal</option></select><label>Passphrase</label><input id="wifiPass" value="${esc(w.password)}"><label>Channel</label><input id="channel" value="${esc(w.channel)}"></div>`;c.querySelector("#security").value=w.security;[["ssid","ssid"],["security","security"],["wifiPass","password"],["channel","channel"]].forEach(([id,k])=>c.querySelector("#"+id).onchange=e=>{w[k]=e.target.value;persist()})}
function makeWindowDraggable(win){const h=win.querySelector(".window-header");let wd=null;h.addEventListener("pointerdown",e=>{if(e.target.closest("button"))return;win.style.zIndex=++z;wd={x:e.clientX-win.offsetLeft,y:e.clientY-win.offsetTop};document.addEventListener("pointermove",mv);document.addEventListener("pointerup",up,{once:true})});function mv(e){if(!wd)return;win.style.left=Math.max(0,Math.min(window.innerWidth-win.offsetWidth,e.clientX-wd.x))+"px";win.style.top=Math.max(0,Math.min(window.innerHeight-win.offsetHeight,e.clientY-wd.y))+"px"}function up(){wd=null;document.removeEventListener("pointermove",mv)}}
function setTool(t){if(state.reconnect&&t!=="select")cancelReconnect();state.tool=t;if(t!=="connect")clearConnectionFlow();["select","connect","delete"].forEach(x=>$(`#${x}Tool`).classList.toggle("active",x===t));status(`Tool: ${t}`);render()}
$("#selectTool").onclick=()=>setTool("select");$("#connectTool").onclick=()=>setTool("connect");$("#deleteTool").onclick=()=>setTool("delete");$("#recomputeBtn").onclick=()=>{render();status("Topology recalculated.")};$("#newBtn").onclick=()=>{if(confirm("Clear the current topology?")){state.devices=[];state.links=[];state.counters={};render();persist()}};$("#saveBtn").onclick=()=>{persist();status("Saved in this browser.")};$("#loadBtn").onclick=()=>{restore();render();status("Saved topology loaded.")};$("#exportBtn").onclick=()=>{const blob=new Blob([JSON.stringify(exportState(),null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="britts-packet-tracer-lab.json";a.click();URL.revokeObjectURL(a.href)};$("#importInput").onchange=async e=>{try{Object.assign(state,JSON.parse(await e.target.files[0].text()));state.reconnect=null;render();persist();status("Lab imported.")}catch{alert("Invalid lab file.")}};
$("#pingTool").onclick=()=>{$("#pingSource").innerHTML=state.devices.map(d=>`<option value="${d.id}">${esc(d.name)}</option>`).join("");$("#pingResult").textContent="";$("#pingDialog").showModal()};$("#runPingBtn").onclick=()=>{$("#pingResult").textContent=simulatePing(state,$("#pingSource").value,$("#pingDestination").value.trim()).output;render();persist()};
document.addEventListener("keydown",e=>{if(e.key==="Escape"){if(state.reconnect)return cancelReconnect();if(drag){drag=null;document.removeEventListener("pointermove",moveDevice);render();return}if(state.tool==="connect"){clearConnectionFlow();render();status("Connection workflow canceled.")}}});
function exportState(){const copy=typeof structuredClone==="function"?structuredClone(state):JSON.parse(JSON.stringify(state));if(copy.reconnect){const l=copy.links.find(x=>x.id===copy.reconnect.linkId);if(l)l[copy.reconnect.side]=copy.reconnect.original;copy.reconnect=null}return copy}
function persist(){localStorage.setItem("brittsPacketTracerV2",JSON.stringify(exportState()))}
function restore(){const raw=localStorage.getItem("brittsPacketTracerV2")||localStorage.getItem("brittsPacketTracer");if(raw){try{Object.assign(state,JSON.parse(raw));state.reconnect=null}catch{}}}
function status(s){$("#statusPanel").textContent=s}
function esc(s){return (s===null||s===undefined?"":String(s)).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
restore();renderPalette();render();
